import Foundation

/// What a downloaded photo already says about itself.
public struct EmbeddedPhotoMetadata: Equatable {
    /// `OffsetTimeOriginal`: seconds east of UTC that the camera's clock was set to. This is the
    /// one thing Lightroom's JSON cannot tell us, and the one thing that makes a capture time an
    /// instant rather than a wall-clock reading.
    public var captureTimeZoneOffset: Int?
    public var hasCaptureDate: Bool
    public var hasCameraInfo: Bool
    public var hasLocation: Bool

    public init(captureTimeZoneOffset: Int? = nil, hasCaptureDate: Bool = false,
                hasCameraInfo: Bool = false, hasLocation: Bool = false) {
        self.captureTimeZoneOffset = captureTimeZoneOffset
        self.hasCaptureDate = hasCaptureDate
        self.hasCameraInfo = hasCameraInfo
        self.hasLocation = hasLocation
    }

    /// True when the file arrived without the tags every camera writes, which is what a rendition
    /// generated by Adobe looks like. Worth saying in the log, because it is why the app then has
    /// to supply the metadata itself.
    public var looksStripped: Bool {
        !hasCaptureDate && !hasCameraInfo
    }
}

/// Reads and writes the metadata embedded in a photo file.
///
/// Implemented with ImageIO on macOS; the core library stays free of it so the sync logic keeps
/// building and testing on Linux, the same arrangement ``PhotoResizing`` uses.
public protocol PhotoMetadataWriting {
    /// What the file already carries. Never throws: a file nothing can be read from is simply a
    /// file that says nothing.
    func embeddedMetadata(fileAt url: URL) -> EmbeddedPhotoMetadata

    /// Fills in the metadata the file is missing, leaving what it already has alone, and returns
    /// the file to import: the same URL when there was nothing to add, or a new file next to it.
    ///
    /// The image data is copied across untouched rather than re-encoded, so this costs no JPEG
    /// quality. Throwing is allowed and not fatal — the caller then imports the photo as it was
    /// served, which is better than not syncing it at all.
    func write(_ metadata: PhotoMetadata, toFileAt url: URL) throws -> URL
}

/// Leaves every photo's metadata as it was served. Used where no image toolkit is available:
/// the sync engine's own tests, and anything running off a Mac.
public struct NoPhotoMetadataWriting: PhotoMetadataWriting {
    public init() {}

    public func embeddedMetadata(fileAt url: URL) -> EmbeddedPhotoMetadata { EmbeddedPhotoMetadata() }

    public func write(_ metadata: PhotoMetadata, toFileAt url: URL) throws -> URL { url }
}
